// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // Extend here when you add iOS, macOS, Windows, Linux configs
      default:
        break;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are only configured for web platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAXDxRnt3mCdKX0Ktyz0hIp3h2aFZAtSMg",
      authDomain: "alhewan-e110c.firebaseapp.com",
      projectId: "alhewan-e110c",
      storageBucket: "alhewan-e110c.firebasestorage.app",
      messagingSenderId: "451198622828",
      appId: "1:451198622828:web:fc6be59691939408664c49",
      measurementId: "G-WNEF6Q53EK"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDi8sTzHEtcUBe_GDip2tpavl7g-pJmrso",
    appId: "1:451198622828:android:219f91cea026868f664c49",
    messagingSenderId: "451198622828",
    projectId: "alhewan-e110c",
    storageBucket: "alhewan-e110c.firebasestorage.app",
  );
}
